[package]
name = "simple_orbit_determination"
version = "0.1.0"
authors = ["Christopher Rabotin <christopher.rabotin@gmail.com>"]

[dependencies]
nyx-space = {path = "../../"}
nalgebra = "0.15"
hifitime = "0.1.4"
csv ="1.0"
